#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(feat|cut|fix|refactor|optimise|build)\(.*\): .*$"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "===================="
  echo "===================="
  echo "===================="
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "<verb in imperative mood>(<scope>): <what was done>"
  echo "Allowed verbs in imperative mood: feat, cut, fix refactor, optimise, build"
  echo "Example: feat(components): add login button"
  echo "===================="
  echo "Your commit message was:"
  echo $message
  echo "===================="
  echo "For more information, check script in .husky/commit-msg"
  echo "===================="
  echo "===================="
  echo "===================="
  exit 1
fi